### ISSUE TITLE
Version 2.0 Development Journey: Let's Dive In! 🚀

### ISSUE THREAD

**Issue by alperenozlu** [alperenozlu/rainmeter-todo#8]
Hi fellas!

I developed this project to pass the time, learn something new, and for my own use. When I improved the project and shared it on GitHub, I expected it to receive less attention. I appreciate everyone who uses, asks questions, comments, and suggests new features for this application.

Today is the time to build new things. Therefore, I want to announce that I have started developing version 2.0.

With the feedback received from you, the improvements I will focus on in the new version will include:
- [ ]  A more understandable code structure
- [ ]  Storing data in a JSON file instead of a TXT file
- [ ]  The fix of the command execution issue in the new task input
- [ ] Resolving language issues in icons (Japanese, Chinese, Korean) (#3)
- [ ]  Handling the wrapping of long texts in tasks (#7, #6)
- [ ] Adding notes and dates to tasks (Note: Not included in version 2.0.0, but I will work on it for future releases). (#4)

Thank you for your interest and assistance. Happy New Year in advance!

**Comment by TheIndianProgrammer** [comment]
Hey @alperenozlu — hope the development of v2.0 is going well!

I just discovered your Skin today and wanted to say: the so-called _bug_ Is honestly a **_fantastic_** _feature_ for my workflow.

> `If Windows commands are entered as a task, the relevant command is triggered.`


I often need to run specific Windows commands, and this behavior gives me another use for the skin!. I was actually surprised (and impressed!) to see it listed under "known bugs" — it felt like a hidden gem 😄

I'm already using it by making a copy of the Skin in Rainmeter and using the to-do list to save my most-used cmds.

If possible, please consider keeping this behavior as an skin variant or toggle in future updates. I'm sure some users like me would really appreciate having it preserved.

Truely a irl 
> it's not a bug, it's a feature

Thanks again for the awesome work!

**Comment by alperenozlu** [comment]
Hey @TheIndianProgrammer,

Thank you for your thoughtful feedback! I really enjoyed reading your comment.

Your use case is a perfect example of the classic 'it's not a bug, it's a feature' mindset 😄 If I can fix this behavior, I’ll make it configurable.

Cheers,
Alperen

**Comment by meglivorn** [comment]
I wanted to say that I just started to use this skin, and very happy with it.
I hope the project is not abandoned, and the features listed will be available. 
I'm mostly interested in the customisation options, since I'd like to integrate the skin to my existing rainmeter setup. It doesn't take much, almost there by default, only the font sizes and lines arrangements (like if the Important or Recurring toggle is on, the trash icon snaps to the right edge, with no margain).

Thanks for the skin, really, it's just what I needed.

**Comment by alperenozlu** [comment]
Hello @meglivorn 

Thank you for your feedback. I’m really happy to hear this kind of feedback, and it truly motivates me. Currently I am quite busy with my business, and I also recently switched to macOS. That's why I can't work on this project actively. 

I have a local branch which contains some of the v2.0 features, but as I said before, I haven't found any free time to finish these features. To sum up, project is not abandoned, but progress is really slow. I promise, I will do my best.
